### ISSUE TITLE
Cannot find method "itemAdd"

### ISSUE THREAD

**Issue by ChaoSXDemon** [dribbleware1/TinyFerdinand#1]
It seems Inventory class is not in a file named "Inventory" but instead in "inventory". I'm not sure what editor you are using but Intellij doesn't allow that and I'm pretty sure this breaks Java. While that's an easy fix, it seems like itemAdd method isn't to be found. Is this code base really out of date?

**Comment by dribbleware1** [comment]
Code is out of date, will be updated in a couple minutes, the inventory class is misnamed i have attempted a number of times to refactor it and for some reason it never sticks although ive never had any issues with this running it in netbeans or as a jar

**Comment by dribbleware1** [comment]
just updated, the addItem method is in the Inventory class now, and the rename on that class seems to have stuck this time as well
