### ISSUE TITLE
Jar file assets

### ISSUE THREAD

**Issue by dribbleware1** [dribbleware1/TinyFerdinand#3]
currently no support for jar file assets

**Comment by ChaoSXDemon** [comment]
Currently the short term work around is to copy the entire "Res" folder to where the Jar file is.

**Comment by ChaoSXDemon** [comment]
Added support to read from JAR in FileUtils.java; However texture assets should be read from externally where the JAR is executed.

**Comment by ChaoSXDemon** [comment]
Forgot to add that I tested the new features by reading all assets from within the JAR
